---
- hosts: secondary_database
  become: true
  become_user: root
  tasks:

  - name: Install mysql-server
    apt:
      name:
       - python3-mysqldb
       - mysql-server
       - mysql-client
      state: latest
      update_cache: yes

  - name: Manage MySQL root password
    no_log: true
    mysql_user:
      login_user: root
      login_password: dbpass$%^
      name: root
      password: dbpass$%^
      check_implicit_admin: true

  - name: Create myadmin user
    mysql_user:
     name: myadmin
     password: dbpass$%^
     login_user: root
     login_password: dbpass$%^
     priv: "*.*:ALL,GRANT"
     state: present

  - name: Copy mysqld.cnf
    template:
     src:  secondary/mysqld.cnf
     dest: /etc/mysql/mysql.conf.d/mysqld.cnf
     mode: 0644
     owner: root
     group: root

  - name: Restart mysql
    service:
     name: mysql
     state: restarted

  - name: create user monitor (mysql)
    shell: |
     mysql -u root -pdbpass$%^ -e
     CREATE USER 'monitor'@'192.168.1.153' IDENTIFIED WITH mysql_native_password BY 'dbpass$%^';
     GRANT ALL PRIVILEGES ON *.* TO 'monitor'@'192.168.1.153';
    args:
     warn: no

  - name: create user appuser (mysql)
    shell: |
     mysql -u root -pdbpass$%^ -e
     CREATE USER 'appuser'@'%' IDENTIFIED WITH mysql_native_password BY 'appuser$%^';
     GRANT ALL PRIVILEGES ON *.* TO 'appuser'@'%';
    args:
     warn: no
