---
- hosts: databases
  become: true
  become_user: root
  tasks:

  - name: Install mysql-server
    apt:
      name:
       - python3-mysqldb
       - mysql-server
       - mysql-client
       #- proxysql
      state: latest
      update_cache: yes

  - name: Manage MySQL root password
    no_log: true
    mysql_user:
      login_user: root
      login_password: dbpass$%^
      name: root
      password: dbpass$%^
      check_implicit_admin: true

  - name: Add and install proxysql repository
    shell: |
     apt-get install -y --no-install-recommends lsb-release wget apt-transport-https ca-certificates gnupg
     wget -O - 'https://repo.proxysql.com/ProxySQL/proxysql-2.4.x/repo_pub_key' | apt-key add - 
     echo deb https://repo.proxysql.com/ProxySQL/proxysql-2.4.x/$(lsb_release -sc)/ ./ | tee /etc/apt/sources.list.d/proxysql.list
     apt-get update
     apt-get install proxysql
    args:
     warn: no

  - name: Start proxysql
    service:
     name: proxysql
     state: started


  
